version: '3'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  zipkin-all-in-one:
    container_name: zipkin
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    restart: always
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - zipkin-all-in-one
      - jaeger-all-in-one
  input-app:
    build:
      context: .
      dockerfile: Dockerfile-input
    ports:
      - "8080:8080"
    environment:
      - ORCHESTRATION_URL=http://orchestrate-app:8081/orchestrate
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - otel-collector
  orchestrate-app:
    build:
      context: .
      dockerfile: Dockerfile-orchestrate
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - WEATHER_API_KEY=ffff2503c96549ea93e195022242604
    depends_on:
      - otel-collector